/********************************************************************
* FitRes_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error FitRes_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableFitRes_Dict();
extern void G__cpp_setup_inheritanceFitRes_Dict();
extern void G__cpp_setup_typetableFitRes_Dict();
extern void G__cpp_setup_memvarFitRes_Dict();
extern void G__cpp_setup_globalFitRes_Dict();
extern void G__cpp_setup_memfuncFitRes_Dict();
extern void G__cpp_setup_funcFitRes_Dict();
extern void G__set_cpp_environmentFitRes_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "FitResults.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__FitRes_DictLN_TClass;
extern G__linked_taginfo G__FitRes_DictLN_TBuffer;
extern G__linked_taginfo G__FitRes_DictLN_TMemberInspector;
extern G__linked_taginfo G__FitRes_DictLN_TObject;
extern G__linked_taginfo G__FitRes_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__FitRes_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FitRes_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__FitRes_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FitRes_DictLN_FitResults;

/* STUB derived class for protected member access */
