/********************************************************************
* myDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error myDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemyDict();
extern void G__cpp_setup_inheritancemyDict();
extern void G__cpp_setup_typetablemyDict();
extern void G__cpp_setup_memvarmyDict();
extern void G__cpp_setup_globalmyDict();
extern void G__cpp_setup_memfuncmyDict();
extern void G__cpp_setup_funcmyDict();
extern void G__set_cpp_environmentmyDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "FitResults.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__myDictLN_TClass;
extern G__linked_taginfo G__myDictLN_TBuffer;
extern G__linked_taginfo G__myDictLN_TMemberInspector;
extern G__linked_taginfo G__myDictLN_TObject;
extern G__linked_taginfo G__myDictLN_TNamed;
extern G__linked_taginfo G__myDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__myDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__myDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__myDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__myDictLN_FitResults;

/* STUB derived class for protected member access */
