/********************************************************************
* PlotRes_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PlotRes_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePlotRes_Dict();
extern void G__cpp_setup_inheritancePlotRes_Dict();
extern void G__cpp_setup_typetablePlotRes_Dict();
extern void G__cpp_setup_memvarPlotRes_Dict();
extern void G__cpp_setup_globalPlotRes_Dict();
extern void G__cpp_setup_memfuncPlotRes_Dict();
extern void G__cpp_setup_funcPlotRes_Dict();
extern void G__set_cpp_environmentPlotRes_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PlotResults.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PlotRes_DictLN_TClass;
extern G__linked_taginfo G__PlotRes_DictLN_TBuffer;
extern G__linked_taginfo G__PlotRes_DictLN_TMemberInspector;
extern G__linked_taginfo G__PlotRes_DictLN_TObject;
extern G__linked_taginfo G__PlotRes_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PlotRes_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PlotRes_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PlotRes_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PlotRes_DictLN_PlotResults;

/* STUB derived class for protected member access */
