//
// File generated by rootcint at Tue May 14 02:30:36 2019

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME PlotRes_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "PlotRes_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void PlotResults_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_PlotResults(void *p = 0);
   static void *newArray_PlotResults(Long_t size, void *p);
   static void delete_PlotResults(void *p);
   static void deleteArray_PlotResults(void *p);
   static void destruct_PlotResults(void *p);
   static void streamer_PlotResults(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::PlotResults*)
   {
      ::PlotResults *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::PlotResults >(0);
      static ::ROOT::TGenericClassInfo 
         instance("PlotResults", ::PlotResults::Class_Version(), "./PlotResults.h", 16,
                  typeid(::PlotResults), ::ROOT::DefineBehavior(ptr, ptr),
                  &::PlotResults::Dictionary, isa_proxy, 0,
                  sizeof(::PlotResults) );
      instance.SetNew(&new_PlotResults);
      instance.SetNewArray(&newArray_PlotResults);
      instance.SetDelete(&delete_PlotResults);
      instance.SetDeleteArray(&deleteArray_PlotResults);
      instance.SetDestructor(&destruct_PlotResults);
      instance.SetStreamerFunc(&streamer_PlotResults);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::PlotResults*)
   {
      return GenerateInitInstanceLocal((::PlotResults*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::PlotResults*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr PlotResults::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *PlotResults::Class_Name()
{
   return "PlotResults";
}

//______________________________________________________________________________
const char *PlotResults::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::PlotResults*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int PlotResults::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::PlotResults*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void PlotResults::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::PlotResults*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *PlotResults::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::PlotResults*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void PlotResults::Streamer(TBuffer &R__b)
{
   // Stream an object of class PlotResults.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> meanKinBin1;
      R__b >> meanKinBin2;
      R__b.ReadStaticArray((float*)kTUncertainties);
      R__b.ReadStaticArray((float*)kTUncertainties1);
      R__b.ReadStaticArray((float*)kTUncertainties2);
      R__b.ReadStaticArray((float*)kTSysUncertainties);
      R__b.ReadStaticArray((float*)kTValues);
      R__b.ReadStaticArray((float*)kTValues1);
      R__b.ReadStaticArray((float*)kTValues2);
      R__b.ReadStaticArray((float*)kTMeans);
      R__b >> numKtValues;
      R__b >> exp;
      R__b >> on_res;
      R__b >> isUds;
      R__b >> isCharm;
      R__b >> isMC;
      R__b >> calcType;
      R__b >> binningType;
      R__b >> pidBin;
      R__b >> chargeBin;
      R__b >> firstKinBin;
      R__b >> secondKinBin;
      R__b >> resultIndex;
      R__b >> mPrint;
      R__b.CheckByteCount(R__s, R__c, PlotResults::IsA());
   } else {
      R__c = R__b.WriteVersion(PlotResults::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << meanKinBin1;
      R__b << meanKinBin2;
      R__b.WriteArray(kTUncertainties, 30);
      R__b.WriteArray(kTUncertainties1, 30);
      R__b.WriteArray(kTUncertainties2, 30);
      R__b.WriteArray(kTSysUncertainties, 30);
      R__b.WriteArray(kTValues, 30);
      R__b.WriteArray(kTValues1, 30);
      R__b.WriteArray(kTValues2, 30);
      R__b.WriteArray(kTMeans, 30);
      R__b << numKtValues;
      R__b << exp;
      R__b << on_res;
      R__b << isUds;
      R__b << isCharm;
      R__b << isMC;
      R__b << calcType;
      R__b << binningType;
      R__b << pidBin;
      R__b << chargeBin;
      R__b << firstKinBin;
      R__b << secondKinBin;
      R__b << resultIndex;
      R__b << mPrint;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void PlotResults::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class PlotResults.
      TClass *R__cl = ::PlotResults::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "meanKinBin1", &meanKinBin1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "meanKinBin2", &meanKinBin2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "kTUncertainties[30]", kTUncertainties);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "kTUncertainties1[30]", kTUncertainties1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "kTUncertainties2[30]", kTUncertainties2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "kTSysUncertainties[30]", kTSysUncertainties);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "kTValues[30]", kTValues);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "kTValues1[30]", kTValues1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "kTValues2[30]", kTValues2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "kTMeans[30]", kTMeans);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "numKtValues", &numKtValues);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "exp", &exp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "on_res", &on_res);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "isUds", &isUds);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "isCharm", &isCharm);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "isMC", &isMC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "calcType", &calcType);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "binningType", &binningType);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pidBin", &pidBin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chargeBin", &chargeBin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "firstKinBin", &firstKinBin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "secondKinBin", &secondKinBin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "resultIndex", &resultIndex);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mPrint", &mPrint);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_PlotResults(void *p) {
      return  p ? new(p) ::PlotResults : new ::PlotResults;
   }
   static void *newArray_PlotResults(Long_t nElements, void *p) {
      return p ? new(p) ::PlotResults[nElements] : new ::PlotResults[nElements];
   }
   // Wrapper around operator delete
   static void delete_PlotResults(void *p) {
      delete ((::PlotResults*)p);
   }
   static void deleteArray_PlotResults(void *p) {
      delete [] ((::PlotResults*)p);
   }
   static void destruct_PlotResults(void *p) {
      typedef ::PlotResults current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_PlotResults(TBuffer &buf, void *obj) {
      ((::PlotResults*)obj)->::PlotResults::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::PlotResults

/********************************************************
* PlotRes_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablePlotRes_Dict();

extern "C" void G__set_cpp_environmentPlotRes_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("PlotResults.h");
  G__cpp_reset_tagtablePlotRes_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevPlotRes_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* PlotResults */
static int G__PlotRes_Dict_168_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PlotResults* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PlotResults[n];
     } else {
       p = new((void*) gvp) PlotResults[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PlotResults;
     } else {
       p = new((void*) gvp) PlotResults;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PlotRes_DictLN_PlotResults));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PlotRes_Dict_168_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const PlotResults& obj = ((PlotResults*) G__getstructoffset())->operator+=(*(PlotResults*) libp->para[0].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PlotRes_Dict_168_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PlotResults*) G__getstructoffset())->print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PlotRes_Dict_168_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((PlotResults*) G__getstructoffset())->doPrint((bool) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((PlotResults*) G__getstructoffset())->doPrint();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PlotRes_Dict_168_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) PlotResults::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PlotRes_Dict_168_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PlotResults::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PlotRes_Dict_168_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) PlotResults::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PlotRes_Dict_168_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      PlotResults::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PlotRes_Dict_168_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PlotResults*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PlotRes_Dict_168_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PlotResults::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PlotRes_Dict_168_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) PlotResults::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PlotRes_Dict_168_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PlotResults::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PlotRes_Dict_168_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) PlotResults::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__PlotRes_Dict_168_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   PlotResults* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new PlotResults(*(PlotResults*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PlotRes_DictLN_PlotResults));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef PlotResults G__TPlotResults;
static int G__PlotRes_Dict_168_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (PlotResults*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((PlotResults*) (soff+(sizeof(PlotResults)*i)))->~G__TPlotResults();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (PlotResults*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((PlotResults*) (soff))->~G__TPlotResults();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__PlotRes_Dict_168_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PlotResults* dest = (PlotResults*) G__getstructoffset();
   *dest = *(PlotResults*) libp->para[0].ref;
   const PlotResults& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* PlotResults */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncPlotRes_Dict {
 public:
  G__Sizep2memfuncPlotRes_Dict(): p(&G__Sizep2memfuncPlotRes_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncPlotRes_Dict::*p)();
};

size_t G__get_sizep2memfuncPlotRes_Dict()
{
  G__Sizep2memfuncPlotRes_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancePlotRes_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__PlotRes_DictLN_PlotResults))) {
     PlotResults *G__Lderived;
     G__Lderived=(PlotResults*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PlotRes_DictLN_PlotResults),G__get_linked_tagnum(&G__PlotRes_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablePlotRes_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__PlotRes_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PlotRes_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PlotRes_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PlotRes_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PlotRes_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__PlotRes_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PlotRes_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PlotRes_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PlotRes_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PlotRes_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* PlotResults */
static void G__setup_memvarPlotResults(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__PlotRes_DictLN_PlotResults));
   { PlotResults *p; p=(PlotResults*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->meanKinBin1)-(long)(p)),102,0,0,-1,-1,-1,1,"meanKinBin1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->meanKinBin2)-(long)(p)),102,0,0,-1,-1,-1,1,"meanKinBin2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->kTUncertainties)-(long)(p)),102,0,0,-1,-1,-1,1,"kTUncertainties[30]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->kTUncertainties1)-(long)(p)),102,0,0,-1,-1,-1,1,"kTUncertainties1[30]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->kTUncertainties2)-(long)(p)),102,0,0,-1,-1,-1,1,"kTUncertainties2[30]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->kTSysUncertainties)-(long)(p)),102,0,0,-1,-1,-1,1,"kTSysUncertainties[30]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->kTValues)-(long)(p)),102,0,0,-1,-1,-1,1,"kTValues[30]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->kTValues1)-(long)(p)),102,0,0,-1,-1,-1,1,"kTValues1[30]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->kTValues2)-(long)(p)),102,0,0,-1,-1,-1,1,"kTValues2[30]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->kTMeans)-(long)(p)),102,0,0,-1,-1,-1,1,"kTMeans[30]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->numKtValues)-(long)(p)),105,0,0,-1,-1,-1,1,"numKtValues=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->exp)-(long)(p)),105,0,0,-1,-1,-1,1,"exp=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->on_res)-(long)(p)),103,0,0,-1,-1,-1,1,"on_res=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->isUds)-(long)(p)),103,0,0,-1,-1,-1,1,"isUds=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->isCharm)-(long)(p)),103,0,0,-1,-1,-1,1,"isCharm=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->isMC)-(long)(p)),103,0,0,-1,-1,-1,1,"isMC=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->calcType)-(long)(p)),105,0,0,-1,-1,-1,1,"calcType=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->binningType)-(long)(p)),105,0,0,-1,-1,-1,1,"binningType=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pidBin)-(long)(p)),105,0,0,-1,-1,-1,1,"pidBin=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->chargeBin)-(long)(p)),105,0,0,-1,-1,-1,1,"chargeBin=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->firstKinBin)-(long)(p)),105,0,0,-1,-1,-1,1,"firstKinBin=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->secondKinBin)-(long)(p)),105,0,0,-1,-1,-1,1,"secondKinBin=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->resultIndex)-(long)(p)),105,0,0,-1,-1,-1,1,"resultIndex=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"mPrint=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PlotRes_DictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarPlotRes_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncPlotResults(void) {
   /* PlotResults */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__PlotRes_DictLN_PlotResults));
   G__memfunc_setup("PlotResults",1169,G__PlotRes_Dict_168_0_1, 105, G__get_linked_tagnum(&G__PlotRes_DictLN_PlotResults), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator+=",980,G__PlotRes_Dict_168_0_2, 117, G__get_linked_tagnum(&G__PlotRes_DictLN_PlotResults), -1, 1, 1, 1, 1, 0, "u 'PlotResults' - 11 - rhs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("print",557,G__PlotRes_Dict_168_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("doPrint",736,G__PlotRes_Dict_168_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'true' print", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__PlotRes_Dict_168_0_5, 85, G__get_linked_tagnum(&G__PlotRes_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&PlotResults::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__PlotRes_Dict_168_0_6, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PlotResults::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__PlotRes_Dict_168_0_7, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&PlotResults::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__PlotRes_Dict_168_0_8, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&PlotResults::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__PlotRes_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__PlotRes_Dict_168_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__PlotRes_Dict_168_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PlotResults::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__PlotRes_Dict_168_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&PlotResults::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__PlotRes_Dict_168_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PlotResults::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__PlotRes_Dict_168_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&PlotResults::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("PlotResults", 1169, G__PlotRes_Dict_168_0_17, (int) ('i'), G__get_linked_tagnum(&G__PlotRes_DictLN_PlotResults), -1, 0, 1, 1, 1, 0, "u 'PlotResults' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~PlotResults", 1295, G__PlotRes_Dict_168_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__PlotRes_Dict_168_0_19, (int) ('u'), G__get_linked_tagnum(&G__PlotRes_DictLN_PlotResults), -1, 1, 1, 1, 1, 0, "u 'PlotResults' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncPlotRes_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalPlotRes_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcPlotRes_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__PlotRes_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__PlotRes_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__PlotRes_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__PlotRes_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__PlotRes_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__PlotRes_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PlotRes_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__PlotRes_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PlotRes_DictLN_PlotResults = { "PlotResults" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablePlotRes_Dict() {
  G__PlotRes_DictLN_TClass.tagnum = -1 ;
  G__PlotRes_DictLN_TBuffer.tagnum = -1 ;
  G__PlotRes_DictLN_TMemberInspector.tagnum = -1 ;
  G__PlotRes_DictLN_TObject.tagnum = -1 ;
  G__PlotRes_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__PlotRes_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PlotRes_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__PlotRes_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PlotRes_DictLN_PlotResults.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablePlotRes_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__PlotRes_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__PlotRes_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__PlotRes_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__PlotRes_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__PlotRes_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__PlotRes_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PlotRes_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__PlotRes_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__PlotRes_DictLN_PlotResults),sizeof(PlotResults),-1,29952,(char*)NULL,G__setup_memvarPlotResults,G__setup_memfuncPlotResults);
}
extern "C" void G__cpp_setupPlotRes_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupPlotRes_Dict()");
  G__set_cpp_environmentPlotRes_Dict();
  G__cpp_setup_tagtablePlotRes_Dict();

  G__cpp_setup_inheritancePlotRes_Dict();

  G__cpp_setup_typetablePlotRes_Dict();

  G__cpp_setup_memvarPlotRes_Dict();

  G__cpp_setup_memfuncPlotRes_Dict();
  G__cpp_setup_globalPlotRes_Dict();
  G__cpp_setup_funcPlotRes_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncPlotRes_Dict();
  return;
}
class G__cpp_setup_initPlotRes_Dict {
  public:
    G__cpp_setup_initPlotRes_Dict() { G__add_setup_func("PlotRes_Dict",(G__incsetup)(&G__cpp_setupPlotRes_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initPlotRes_Dict() { G__remove_setup_func("PlotRes_Dict"); }
};
G__cpp_setup_initPlotRes_Dict G__cpp_setup_initializerPlotRes_Dict;

